services:
  - type: web
    name: smartpest-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn smartpest_backend.wsgi:application
    envVars:
      - key: DEBUG
        value: 'False'
      - key: PYTHON_VERSION
        value: 3.10
    plan: free
